name: Node.js

variables:
  - name: node-version
    value: 14


on:
  pull_request:
    branches:
      - $default-branch
      - refs/tags/*ss
  push:
    branches:
      - $default-branch
      - refs/tags/*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ variables.node-version }}
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/setup-node@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          node-version: ${{ variables.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
